import React, { useRef, useEffect } from 'react';
import { ForceGraph3D } from 'react-force-graph';
import { borderRadius } from '../Theme';


export const ThreeDGraph = () => {
    const fgRef = useRef<any>();

    return (
        <div style={{
            width: '800px',
            height: '400px',
            minHeight: '300px',
            position: 'relative',
            borderRadius: borderRadius,
            overflow: 'hidden',
        }}>
            <ForceGraph3D
                ref={fgRef}
                backgroundColor="#000003"
                width={800}
                height={400}
                graphData={temporalLifeMap}
                nodeLabel="id"
                nodeAutoColorBy="group"
                linkWidth={1}
                linkOpacity={0.5}
            />
        </div>
    );
};

export const temporalLifeMap = {
    "nodes": [
        { "id": "Birth", "group": 0 },
        { "id": "EarlyChildhood", "group": 0 },
        { "id": "FirstDayOfSchool", "group": 1 },
        { "id": "LearnedToWalk", "group": 0 },
        { "id": "LearnedToSpeak", "group": 0 },
        { "id": "FamilyMoved", "group": 2 },
        { "id": "StartedPlayingSports", "group": 3 },
        { "id": "MadeFirstFriend", "group": 4 },
        { "id": "LostFirstFriend", "group": 4 },
        { "id": "FirstPet", "group": 5 },
        { "id": "FamilyPetMoved", "group": 5 },
        { "id": "LearnedToRideBike", "group": 0 },
        { "id": "FavoriteTeacher", "group": 1 },
        { "id": "ChangedSchool", "group": 2 },
        { "id": "WonFirstAward", "group": 3 },
        { "id": "JoinedClubs", "group": 3 },
        { "id": "FirstSchoolDance", "group": 4 },
        { "id": "GraduatedElementary", "group": 1 },
        { "id": "HighSchoolStart", "group": 1 },
        { "id": "SummerJob", "group": 6 },
        { "id": "FirstLove", "group": 4 },
        { "id": "BrokenHeart", "group": 4 },
        { "id": "AcademicAchievement", "group": 3 },
        { "id": "Volunteering", "group": 7 },
        { "id": "SummerCamp", "group": 3 },
        { "id": "LearnedToDrive", "group": 0 },
        { "id": "FirstCar", "group": 6 },
        { "id": "FirstJob", "group": 6 },
        { "id": "CollegeDecision", "group": 2 },
        { "id": "AppliedToCollege", "group": 2 },
        { "id": "AcceptedToCollege", "group": 2 },
        { "id": "RejectedFromCollege", "group": 2 },
        { "id": "GapYear", "group": 8 },
        { "id": "TraveledAbroad", "group": 8 },
        { "id": "StartedCollege", "group": 1 },
        { "id": "RoommateConflict", "group": 4 },
        { "id": "Internship", "group": 6 },
        { "id": "ChangedMajor", "group": 2 },
        { "id": "GraduatedCollege", "group": 1 },
        { "id": "FirstFullTimeJob", "group": 6 },
        { "id": "PromotedAtWork", "group": 6 },
        { "id": "FirstApartment", "group": 2 },
        { "id": "FirstRentPayment", "group": 2 },
        { "id": "MovedToCity", "group": 2 },
        { "id": "MetSignificantOther", "group": 4 },
        { "id": "Engagement", "group": 4 },
        { "id": "Marriage", "group": 4 },
        { "id": "BoughtFirstHouse", "group": 2 },
        { "id": "FinancialCrisis", "group": 9 },
        { "id": "CareerChange", "group": 6 },
        { "id": "StartedBusiness", "group": 6 },
        { "id": "BusinessFailure", "group": 9 },
        { "id": "HealthIssue", "group": 10 },
        { "id": "RecoveredHealth", "group": 10 },
        { "id": "PromotedAgain", "group": 6 },
        { "id": "BoughtSecondHouse", "group": 2 },
        { "id": "FirstChild", "group": 11 },
        { "id": "SecondChild", "group": 11 },
        { "id": "Divorce", "group": 4 },
        { "id": "MovedOut", "group": 2 },
        { "id": "NewRelationship", "group": 4 },
        { "id": "AdoptedPet", "group": 5 },
        { "id": "StartedGraduateSchool", "group": 1 },
        { "id": "CompletedGraduateSchool", "group": 1 },
        { "id": "PublishedFirstPaper", "group": 3 },
        { "id": "ResearchGrant", "group": 3 },
        { "id": "ConferencePresentation", "group": 3 },
        { "id": "ReceivedTenure", "group": 3 },
        { "id": "FirstGrandchild", "group": 11 },
        { "id": "Retirement", "group": 6 },
        { "id": "TravelDuringRetirement", "group": 8 },
        { "id": "VolunteerRetirement", "group": 7 },
        { "id": "StartedHobby", "group": 12 },
        { "id": "HobbyAchievement", "group": 12 },
        { "id": "LostJob", "group": 9 },
        { "id": "FoundNewJob", "group": 6 },
        { "id": "SecondMarriage", "group": 4 },
        { "id": "StartedNewBusiness", "group": 6 },
        { "id": "BusinessSuccess", "group": 6 },
        { "id": "BusinessExpansion", "group": 6 },
        { "id": "PhilanthropyStart", "group": 7 },
        { "id": "DonatedToCharity", "group": 7 },
        { "id": "MentoredYouth", "group": 7 },
        { "id": "HealthMaintenance", "group": 10 },
        { "id": "FamilyReunion", "group": 4 },
        { "id": "FirstTravelSolo", "group": 8 },
        { "id": "MasteredNewSkill", "group": 12 },
        { "id": "ProfessionalCertification", "group": 3 },
        { "id": "PublicSpeakingEngagement", "group": 3 },
        { "id": "AuthoredBook", "group": 3 },
        { "id": "PersonalMilestone", "group": 11 },
        { "id": "CommunityLeadership", "group": 7 },
        { "id": "EnvironmentalAdvocacy", "group": 7 },
        { "id": "CulturalEngagement", "group": 8 },
        { "id": "RetirementCelebration", "group": 11 },
        { "id": "LegacyPlanning", "group": 10 },
        { "id": "EstateManagement", "group": 10 },
        { "id": "FinalHealthCheck", "group": 10 },
        { "id": "SpiritualGrowth", "group": 13 },
        { "id": "SecondChild", "group": 11 },
        { "id": "AdoptionProcess", "group": 11 },
        { "id": "GraduateThesis", "group": 1 },
        { "id": "FirstPatent", "group": 3 },
        { "id": "InnovationAward", "group": 3 },
        { "id": "PatentCommercialization", "group": 6 },
        { "id": "StartupFunding", "group": 6 },
        { "id": "StartupLaunch", "group": 6 },
        { "id": "StartupGrowth", "group": 6 },
        { "id": "GlobalExpansion", "group": 6 },
        { "id": "HealthAwareness", "group": 10 },
        { "id": "MentalHealthSupport", "group": 10 },
        { "id": "FirstMeditation", "group": 13 },
        { "id": "YogaPractice", "group": 13 },
        { "id": "FirstMarathon", "group": 3 },
        { "id": "MarathonTraining", "group": 3 },
        { "id": "TriathlonParticipation", "group": 3 },
        { "id": "CyclingAchievement", "group": 3 },
        { "id": "FirstArtExhibition", "group": 12 },
        { "id": "ArtCollectionStart", "group": 12 },
        { "id": "CulinaryAchievement", "group": 12 },
        { "id": "FirstMusicPerformance", "group": 12 },
        { "id": "MusicAlbumRelease", "group": 12 },
        { "id": "DanceCertification", "group": 12 },
        { "id": "LanguageLearning", "group": 12 },
        { "id": "MultilingualAchievement", "group": 12 },
        { "id": "FirstBlogPost", "group": 12 },
        { "id": "BlogGrowth", "group": 12 },
        { "id": "PodcastLaunch", "group": 12 },
        { "id": "PodcastSuccess", "group": 12 },
        { "id": "OnlineCourseCreation", "group": 12 },
        { "id": "OnlineCourseLaunch", "group": 12 },
        { "id": "CertificationTeaching", "group": 12 },
        { "id": "FirstPublicWorkshop", "group": 12 },
        { "id": "WorkshopSeries", "group": 12 },
        { "id": "BookClubFounder", "group": 12 },
        { "id": "FirstBookClubMeeting", "group": 12 },
        { "id": "CommunityGardenStart", "group": 7 },
        { "id": "GardenMaintenance", "group": 7 },
        { "id": "SustainableLivingAdopted", "group": 7 },
        { "id": "ZeroWasteLifestyle", "group": 7 },
        { "id": "RenewableEnergyInstallation", "group": 7 },
        { "id": "FirstRenewableProject", "group": 7 },
        { "id": "EnergyEfficiencyUpgrade", "group": 7 },
        { "id": "EnvironmentalWorkshop", "group": 7 },
        { "id": "ClimateActionParticipation", "group": 7 },
        { "id": "PoliticalEngagement", "group": 14 },
        { "id": "FirstVote", "group": 14 },
        { "id": "CivicDutyParticipation", "group": 14 },
        { "id": "LocalGovernmentInvolvement", "group": 14 },
        { "id": "FirstElectionCampaign", "group": 14 },
        { "id": "VoterRegistration", "group": 14 },
        { "id": "CandidacyLaunch", "group": 14 },
        { "id": "ElectionVictory", "group": 14 },
        { "id": "PolicyImplementation", "group": 14 },
        { "id": "LegislationDrafting", "group": 14 },
        { "id": "FirstLawPassed", "group": 14 },
        { "id": "InternationalDiplomacy", "group": 14 },
        { "id": "PeaceNegotiation", "group": 14 },
        { "id": "HumanRightsAdvocacy", "group": 14 },
        { "id": "DisasterReliefParticipation", "group": 7 },
        { "id": "FirstDisasterResponse", "group": 7 },
        { "id": "CrisisManagementTraining", "group": 7 },
        { "id": "LeadershipDevelopment", "group": 3 },
        { "id": "MentorshipProgramStart", "group": 7 },
        { "id": "MentorshipProgramGrowth", "group": 7 },
        { "id": "FirstMentorshipSuccess", "group": 7 },
        { "id": "TechnologyAdoption", "group": 15 },
        { "id": "FirstTechStartup", "group": 6 },
        { "id": "TechInnovationAward", "group": 6 },
        { "id": "AIProjectLaunch", "group": 15 },
        { "id": "AIProjectSuccess", "group": 15 },
        { "id": "BlockchainIntegration", "group": 15 },
        { "id": "CyberSecurityCertification", "group": 15 },
        { "id": "FirstCyberSecurityProject", "group": 15 },
        { "id": "DataScienceAchievement", "group": 15 },
        { "id": "MachineLearningModel", "group": 15 },
        { "id": "BigDataAnalysis", "group": 15 },
        { "id": "CloudComputingImplementation", "group": 15 },
        { "id": "IoTProjectLaunch", "group": 15 },
        { "id": "SmartHomeSetup", "group": 15 },
        { "id": "FirstSmartDevice", "group": 15 },
        { "id": "VRExperienceLaunch", "group": 15 },
        { "id": "ARApplicationDevelopment", "group": 15 },
        { "id": "QuantumComputingExploration", "group": 15 },
        { "id": "FirstQuantumExperiment", "group": 15 },
        { "id": "SaaSProductLaunch", "group": 6 },
        { "id": "FirstSaaSCustomer", "group": 6 },
        { "id": "SaaSGrowthMilestone", "group": 6 },
        { "id": "FirstIPO", "group": 6 },
        { "id": "MarketExpansionPlan", "group": 6 },
        { "id": "FirstInternationalOffice", "group": 6 },
        { "id": "GlobalMarketEntry", "group": 6 },
        { "id": "SustainabilityInitiative", "group": 7 },
        { "id": "GreenBuildingCertification", "group": 7 },
        { "id": "CarbonNeutralGoal", "group": 7 },
        { "id": "RenewableEnergyPurchase", "group": 7 },
        { "id": "GreenTechnologyAdoption", "group": 7 },
        { "id": "SustainableSupplyChain", "group": 7 },
        { "id": "CircularEconomyImplementation", "group": 7 },
        { "id": "FirstCircularProject", "group": 7 },
        { "id": "WasteReductionProgram", "group": 7 },
        { "id": "RecyclingInitiative", "group": 7 },
        { "id": "FirstRecyclingFacility", "group": 7 },
        { "id": "OrganicFarmingStart", "group": 7 },
        { "id": "CommunitySupportedAgriculture", "group": 7 },
        { "id": "FarmersMarketParticipation", "group": 7 },
        { "id": "LocalFoodSourcing", "group": 7 },
        { "id": "HydroponicsExperiment", "group": 7 },
        { "id": "UrbanFarmingProject", "group": 7 },
        { "id": "RenewableEnergyWorkshop", "group": 7 },
        { "id": "FirstSolarPanelInstallation", "group": 7 },
        { "id": "WindTurbineProject", "group": 7 },
        { "id": "EnergyStorageSolution", "group": 7 },
        { "id": "SmartGridIntegration", "group": 7 },
        { "id": "FirstSmartGridImplementation", "group": 7 },
        { "id": "ElectricVehicleAdoption", "group": 15 },
        { "id": "FirstElectricCar", "group": 15 },
        { "id": "EVChargingStationSetup", "group": 15 },
        { "id": "AutonomousVehicleExperiment", "group": 15 },
        { "id": "TransportationEfficiency", "group": 15 },
        { "id": "PublicTransportUpgrade", "group": 15 },
        { "id": "FirstPublicTransportProject", "group": 15 },
        { "id": "BicycleInfrastructureDevelopment", "group": 15 },
        { "id": "BikeSharingProgram", "group": 15 },
        { "id": "PedestrianZoneCreation", "group": 15 },
        { "id": "FirstPedestrianProject", "group": 15 },
        { "id": "TrafficFlowOptimization", "group": 15 },
        { "id": "SmartTrafficLights", "group": 15 },
        { "id": "FirstSmartTrafficLight", "group": 15 },
        { "id": "TransportationDataAnalysis", "group": 15 },
        { "id": "Mobility-as-a-ServiceLaunch", "group": 15 },
        { "id": "FirstMaaSUser", "group": 15 },
        { "id": "PublicTransitMobileApp", "group": 15 },
        { "id": "FirstAppDownload", "group": 15 },
        { "id": "AppUserGrowth", "group": 15 },
        { "id": "TransportationPolicyReform", "group": 14 },
        { "id": "FirstPolicyProposal", "group": 14 },
        { "id": "PolicyAdoption", "group": 14 },
        { "id": "PolicyImpactAssessment", "group": 14 },
        { "id": "FirstPolicyImpact", "group": 14 },
        { "id": "InternationalPolicyCollaboration", "group": 14 },
        { "id": "GlobalPolicyConference", "group": 14 },
        { "id": "FirstGlobalPolicyAgreement", "group": 14 },
        { "id": "PolicySustainabilityFramework", "group": 14 },
        { "id": "SustainableDevelopmentGoalAchievement", "group": 14 },
        { "id": "FirstSDGImplemented", "group": 14 },
        { "id": "SDGProgressReport", "group": 14 },
        { "id": "CommunityFeedbackIntegration", "group": 14 },
        { "id": "PolicyRevision", "group": 14 },
        { "id": "FirstPolicyRevision", "group": 14 },
        { "id": "PolicyEffectivenessReview", "group": 14 },
        { "id": "PolicyScaling", "group": 14 },
        { "id": "RegionalPolicyAdoption", "group": 14 },
        { "id": "LocalPolicyImplementation", "group": 14 },
        { "id": "PolicySustainabilityAward", "group": 14 },
        { "id": "PolicyInnovationRecognition", "group": 14 },
        { "id": "PolicyLeadershipRole", "group": 14 },
        { "id": "FirstLeadershipRole", "group": 14 },
        { "id": "LeadershipConferenceAttendance", "group": 14 },
        { "id": "LeadershipWorkshop", "group": 14 },
        { "id": "FirstLeadershipWorkshop", "group": 14 },
        { "id": "LeadershipCertification", "group": 14 },
        { "id": "FirstLeadershipCertification", "group": 14 },
        { "id": "LeadershipRoleExpansion", "group": 14 },
        { "id": "GlobalLeadershipConference", "group": 14 },
        { "id": "FirstGlobalLeadershipPresentation", "group": 14 },
        { "id": "LeadershipMentorship", "group": 14 },
        { "id": "FirstLeadershipMentee", "group": 14 },
        { "id": "LeadershipGrowthPlan", "group": 14 },
        { "id": "Sabbatical", "group": 8 },
        { "id": "SabbaticalTravel", "group": 8 },
        { "id": "SabbaticalResearch", "group": 8 },
        { "id": "SabbaticalWriting", "group": 8 },
        { "id": "PostRetirementEngagement", "group": 11 },
        { "id": "LegacyProjectStart", "group": 11 },
        { "id": "FirstLegacyContribution", "group": 11 },
        { "id": "LegacyFoundationLaunch", "group": 11 },
        { "id": "FoundationFirstGrant", "group": 11 },
        { "id": "FinalProjectCompletion", "group": 11 },
        { "id": "LifeReflection", "group": 13 },
        { "id": "SpiritualRetreat", "group": 13 },
        { "id": "LifeAchievementRecognition", "group": 11 },
        { "id": "CommunityCelebration", "group": 11 },
        { "id": "FinalLegacyCelebration", "group": 11 },
        { "id": "EstateFinalization", "group": 10 },
        { "id": "FamilyInheritance", "group": 10 },
        { "id": "FinalGoodbye", "group": 11 },
        { "id": "MemorialService", "group": 11 },
        { "id": "PosthumousRecognition", "group": 11 },
        { "id": "LastWillExecution", "group": 10 },
        { "id": "DigitalLegacyCreation", "group": 13 },
        { "id": "FirstDigitalLegacy", "group": 13 },
        { "id": "LegacyMediaRelease", "group": 13 },
        { "id": "PosthumousPublication", "group": 13 },
        { "id": "LegacyFoundationEndowment", "group": 11 },
        { "id": "PhilanthropicLegacy", "group": 11 },
        { "id": "LegacySchoolScholarship", "group": 11 },
        { "id": "CommunityLegacyProject", "group": 11 },
        { "id": "GlobalLegacyImpact", "group": 11 },
        { "id': 'FirstCharitableDonation', 'group': 7 },
        { 'id': 'SustainedCharitableSupport', 'group': 7 },
        { 'id': 'CharitableFoundation', 'group': 7 },
        { 'id': 'FirstFoundationGrant', 'group': 7 },
        { 'id': 'PhilanthropicRecognition', 'group': 7 },
        { 'id': 'SustainablePhilanthropy', 'group': 7 },
        { 'id': 'ImpactInvestmentStart', 'group': 7 },
        { 'id': 'FirstImpactInvestment', 'group': 7 },
        // Add additional nodes as needed to reach at least 200
    ],
    "links": [
        { "source": "Birth", "target": "EarlyChildhood", "value": 1 },
        { "source": "EarlyChildhood", "target": "LearnedToWalk", "value": 1 },
        { "source": "EarlyChildhood", "target": "LearnedToSpeak", "value": 1 },
        { "source": "LearnedToWalk", "target": "FirstDayOfSchool", "value": 2 },
        { "source": "LearnedToSpeak", "target": "FirstDayOfSchool", "value": 2 },
        { "source": "LearnedToWalk", "target": "LearnedToRideBike", "value": 1 },
        { "source": "LearnedToSpeak", "target": "MadeFirstFriend", "value": 1 },
        { "source": "FamilyMoved", "target": "ChangedSchool", "value": 1 },
        { "source": "FirstDayOfSchool", "target": "MadeFirstFriend", "value": 2 },
        { "source": "FirstDayOfSchool", "target": "FavoriteTeacher", "value": 2 },
        { "source": "LearnedToRideBike", "target": "StartedPlayingSports", "value": 1 },
        { "source": "MadeFirstFriend", "target": "LostFirstFriend", "value": 1 },
        { "source": "MadeFirstFriend", "target": "FirstPet", "value": 1 },
        { "source": "FirstPet", "target": "FamilyPetMoved", "value": 1 },
        { "source": "FavoriteTeacher", "target": "AcademicAchievement", "value": 3 },
        { "source": "FirstDayOfSchool", "target": "GraduatedElementary", "value": 3 },
        { "source": "GraduatedElementary", "target": "HighSchoolStart", "value": 1 },
        { "source": "HighSchoolStart", "target": "SummerJob", "value": 2 },
        { "source": "HighSchoolStart", "target": "JoinedClubs", "value": 2 },
        { "source": "JoinedClubs", "target": "WonFirstAward", "value": 2 },
        { "source": "SummerJob", "target": "FirstLove", "value": 1 },
        { "source": "FirstLove", "target": "BrokenHeart", "value": 1 },
        { "source": "AcademicAchievement", "target": "Volunteering", "value": 1 },
        { "source": "SummerJob", "target": "SummerCamp", "value": 1 },
        { "source": "SummerCamp", "target": "LearnedToDrive", "value": 2 },
        { "source": "LearnedToDrive", "target": "FirstCar", "value": 2 },
        { "source": "FirstCar", "target": "FirstJob", "value": 2 },
        { "source": "FirstJob", "target": "FirstFullTimeJob", "value": 3 },
        { "source": "FirstFullTimeJob", "target": "PromotedAtWork", "value": 2 },
        { "source": "FirstJob", "target": "Internship", "value": 1 },
        { "source": "Internship", "target": "FirstFullTimeJob", "value": 1 },
        { "source": "HighSchoolStart", "target": "ChangedSchool", "value": 1 },
        { "source": "ChangedSchool", "target": "HighSchoolStart", "value": 1 },
        { "source": "ChangedSchool", "target": "AcademicAchievement", "value": 1 },
        { "source": "FirstSchoolDance", "target": "FirstLove", "value": 1 },
        { "source": "FirstSchoolDance", "target": "MadeFirstFriend", "value": 1 },
        { "source": "JoinedClubs", "target": "LeadershipDevelopment", "value": 1 },
        { "source": "LeadershipDevelopment", "target": "AcademicAchievement", "value": 1 },
        { "source": "FirstFullTimeJob", "target": "FirstApartment", "value": 2 },
        { "source": "FirstApartment", "target": "FirstRentPayment", "value": 1 },
        { "source": "FirstRentPayment", "target": "MovedToCity", "value": 1 },
        { "source": "MovedToCity", "target": "MetSignificantOther", "value": 2 },
        { "source": "MetSignificantOther", "target": "Engagement", "value": 2 },
        { "source": "Engagement", "target": "Marriage", "value": 2 },
        { "source": "Marriage", "target": "BoughtFirstHouse", "value": 3 },
        { "source": "Marriage", "target": "FirstChild", "value": 3 },
        { "source": "BoughtFirstHouse", "target": "FinancialCrisis", "value": 1 },
        { "source": "FinancialCrisis", "target": "CareerChange", "value": 2 },
        { "source": "CareerChange", "target": "StartedBusiness", "value": 2 },
        { "source": "StartedBusiness", "target": "BusinessFailure", "value": 1 },
        { "source": "BusinessFailure", "target": "RecoveredHealth", "value": 1 },
        { "source": "HealthIssue", "target": "RecoveredHealth", "value": 1 },
        { "source": "RecoveredHealth", "target": "PromotedAgain", "value": 1 },
        { "source": "PromotedAgain", "target": "BoughtSecondHouse", "value": 2 },
        { "source": "BoughtSecondHouse", "target": "SecondChild", "value": 2 },
        { "source": "SecondChild", "target": "AdoptionProcess", "value": 1 },
        { "source": "AdoptionProcess", "target": "AdoptedPet", "value": 1 },
        { "source": "StartedGraduateSchool", "target": "CompletedGraduateSchool", "value": 2 },
        { "source": "CompletedGraduateSchool", "target": "PublishedFirstPaper", "value": 2 },
        { "source": "PublishedFirstPaper", "target": "ResearchGrant", "value": 1 },
        { "source": "ResearchGrant", "target": "ConferencePresentation", "value": 1 },
        { "source": "ConferencePresentation", "target": "ReceivedTenure", "value": 2 },
        { "source": "ReceivedTenure", "target": "FirstGrandchild", "value": 3 },
        { "source": "ReceivedTenure", "target": "Retirement", "value": 3 },
        { "source": "Retirement", "target": "TravelDuringRetirement", "value": 2 },
        { "source": "Retirement", "target": "VolunteerRetirement", "value": 2 },
        { "source": "StartedHobby", "target": "HobbyAchievement", "value": 2 },
        { "source": "HobbyAchievement", "target": "FirstArtExhibition", "value": 1 },
        { "source": "FirstArtExhibition", "target": "ArtCollectionStart", "value": 1 },
        { "source": "ArtCollectionStart", "target": "CulinaryAchievement", "value": 1 },
        { "source": "CulinaryAchievement", "target": "FirstMusicPerformance", "value": 1 },
        { "source": "FirstMusicPerformance", "target": "MusicAlbumRelease", "value": 1 },
        { "source": "MusicAlbumRelease", "target": "DanceCertification", "value": 1 },
        { "source": "DanceCertification", "target": "LanguageLearning", "value": 1 },
        { "source": "LanguageLearning", "target": "MultilingualAchievement", "value": 1 },
        { "source": "MultilingualAchievement", "target": "FirstBlogPost", "value": 1 },
        { "source": "FirstBlogPost", "target": "BlogGrowth", "value": 1 },
        { "source": "BlogGrowth", "target": "PodcastLaunch", "value": 1 },
        { "source": "PodcastLaunch", "target": "PodcastSuccess", "value": 1 },
        { "source": "PodcastSuccess", "target": "OnlineCourseCreation", "value": 1 },
        { "source": "OnlineCourseCreation", "target": "OnlineCourseLaunch", "value": 1 },
        { "source": "OnlineCourseLaunch", "target": "CertificationTeaching", "value": 1 },
        { "source": "CertificationTeaching", "target": "FirstPublicWorkshop", "value": 1 },
        { "source": "FirstPublicWorkshop", "target": "WorkshopSeries", "value": 1 },
        { "source": "WorkshopSeries", "target": "BookClubFounder", "value": 1 },
        { "source": "BookClubFounder", "target": "FirstBookClubMeeting", "value": 1 },
        { "source": "FirstBookClubMeeting", "target": "CommunityGardenStart", "value": 1 },
        { "source": "CommunityGardenStart", "target": "GardenMaintenance", "value": 1 },
        { "source": "GardenMaintenance", "target": "SustainableLivingAdopted", "value": 2 },
        { "source": "SustainableLivingAdopted", "target": "ZeroWasteLifestyle", "value": 1 },
        { "source": "ZeroWasteLifestyle", "target": "RenewableEnergyInstallation", "value": 1 },
        { "source": "RenewableEnergyInstallation", "target": "FirstRenewableProject", "value": 1 },
        { "source": "FirstRenewableProject", "target": "WasteReductionProgram", "value": 1 },
        { "source": "WasteReductionProgram", "target": "RecyclingInitiative", "value": 1 },
        { "source": "RecyclingInitiative", "target": "FirstRecyclingFacility", "value": 1 },
        { "source": "FirstRecyclingFacility", "target": "OrganicFarmingStart", "value": 1 },
        { "source": "OrganicFarmingStart", "target": "CommunitySupportedAgriculture", "value": 1 },
        { "source": "CommunitySupportedAgriculture", "target": "FarmersMarketParticipation", "value": 1 },
        { "source": "FarmersMarketParticipation", "target": "LocalFoodSourcing", "value": 1 },
        { "source": "LocalFoodSourcing", "target": "HydroponicsExperiment", "value": 1 },
        { "source": "HydroponicsExperiment", "target": "UrbanFarmingProject", "value": 1 },
        { "source": "UrbanFarmingProject", "target": "RenewableEnergyWorkshop", "value": 1 },
        { "source": "RenewableEnergyWorkshop", "target": "FirstSolarPanelInstallation", "value": 1 },
        { "source": "FirstSolarPanelInstallation", "target": "WindTurbineProject", "value": 1 },
        { "source": "WindTurbineProject", "target": "EnergyStorageSolution", "value": 1 },
        { "source": "EnergyStorageSolution", "target": "SmartGridIntegration", "value": 1 },
        { "source": "SmartGridIntegration", "target": "FirstSmartGridImplementation", "value": 1 },
        { "source": "SmartGridIntegration", "target": "RenewableEnergyPurchase", "value": 1 },
        { "source": "RenewableEnergyPurchase", "target": "GreenTechnologyAdoption", "value": 1 },
        { "source": "GreenTechnologyAdoption", "target": "SustainableSupplyChain", "value": 1 },
        { "source": "SustainableSupplyChain", "target": "CircularEconomyImplementation", "value": 1 },
        { "source": "CircularEconomyImplementation", "target": "FirstCircularProject", "value": 1 },
        { "source": "FirstCircularProject", "target": "RecyclingInitiative", "value": 1 },
        { "source": "FirstCircularProject", "target": "WasteReductionProgram", "value": 1 },
        { "source": "FirstCar", "target": "ElectricVehicleAdoption", "value": 2 },
        { "source": "ElectricVehicleAdoption", "target": "FirstElectricCar", "value": 1 },
        { "source": "FirstElectricCar", "target": "EVChargingStationSetup", "value": 1 },
        { "source": "EVChargingStationSetup", "target": "AutonomousVehicleExperiment", "value": 1 },
        { "source": "AutonomousVehicleExperiment", "target": "TransportationEfficiency", "value": 1 },
        { "source": "TransportationEfficiency", "target": "PublicTransportUpgrade", "value": 1 },
        { "source": "PublicTransportUpgrade", "target": "FirstPublicTransportProject", "value": 1 },
        { "source": "FirstPublicTransportProject", "target": "BicycleInfrastructureDevelopment", "value": 1 },
        { "source": "BicycleInfrastructureDevelopment", "target": "BikeSharingProgram", "value": 1 },
        { "source": "BikeSharingProgram", "target": "PedestrianZoneCreation", "value": 1 },
        { "source": "PedestrianZoneCreation", "target": "FirstPedestrianProject", "value": 1 },
        { "source": "FirstPedestrianProject", "target": "TrafficFlowOptimization", "value": 1 },
        { "source": "TrafficFlowOptimization", "target": "SmartTrafficLights", "value": 1 },
        { "source": "SmartTrafficLights", "target": "FirstSmartTrafficLight", "value": 1 },
        { "source": "FirstSmartTrafficLight", "target": "TransportationDataAnalysis", "value": 1 },
        { "source": "TransportationDataAnalysis", "target": "Mobility-as-a-ServiceLaunch", "value": 1 },
        { "source": "Mobility-as-a-ServiceLaunch", "target": "FirstMaaSUser", "value": 1 },
        { "source": "FirstMaaSUser", "target": "PublicTransitMobileApp", "value": 1 },
        { "source": "PublicTransitMobileApp", "target": "FirstAppDownload", "value": 1 },
        { "source": "FirstAppDownload", "target": "AppUserGrowth", "value": 1 },
        { "source": "AppUserGrowth", "target": "TransportationPolicyReform", "value": 2 },
        { "source": "TransportationPolicyReform", "target": "FirstPolicyProposal", "value": 1 },
        { "source": "FirstPolicyProposal", "target": "PolicyAdoption", "value": 1 },
        { "source": "PolicyAdoption", "target": "PolicyEffectivenessReview", "value": 1 },
        { "source": "PolicyEffectivenessReview", "target": "PolicyRevision", "value": 1 },
        { "source": "PolicyRevision", "target": "PolicyScaling", "value": 1 },
        { "source": "PolicyScaling", "target": "RegionalPolicyAdoption", "value": 1 },
        { "source": "RegionalPolicyAdoption", "target': 'LocalPolicyImplementation', 'value': 1 },
        { 'source': 'LocalPolicyImplementation', 'target': 'PolicySustainabilityFramework', 'value': 1 },
        { 'source': 'PolicySustainabilityFramework', 'target': 'SustainableDevelopmentGoalAchievement', 'value': 1 },
        { 'source': 'SustainableDevelopmentGoalAchievement', 'target': 'FirstSDGImplemented', 'value': 1 },
        { 'source': 'FirstSDGImplemented', 'target': 'SDGProgressReport', 'value': 1 },
        { 'source': 'SDGProgressReport', 'target': 'CommunityFeedbackIntegration', 'value': 1 },
        { 'source': 'CommunityFeedbackIntegration', 'target': 'PolicyRevision', 'value': 1 },
        { 'source': 'PolicyRevision', 'target': 'PolicyEffectivenessReview', 'value': 1 },
        { 'source': 'PolicyRevision', 'target': 'PolicyScaling', 'value': 1 },
        { 'source': 'CommunityFeedbackIntegration', 'target': 'PolicyScaling', 'value': 1 },
        { 'source': 'PolicyScaling', 'target': 'PolicyAdoption', 'value': 1 },
        { 'source': 'PolicyAdoption', 'target': 'PolicyLeadershipRole', 'value': 1 },
        { 'source': 'PolicyLeadershipRole', 'target': 'FirstLeadershipRole', 'value': 1 },
        { 'source': 'FirstLeadershipRole', 'target': 'LeadershipConferenceAttendance', 'value': 1 },
        { 'source': 'LeadershipConferenceAttendance', 'target': 'LeadershipWorkshop', 'value': 1 },
        { 'source': 'LeadershipWorkshop', 'target': 'FirstLeadershipWorkshop', 'value': 1 },
        { 'source': 'FirstLeadershipWorkshop', 'target': 'LeadershipCertification', 'value': 1 },
        { 'source': 'LeadershipCertification', 'target': 'FirstLeadershipCertification', 'value': 1 },
        { 'source': 'FirstLeadershipCertification', 'target': 'LeadershipRoleExpansion', 'value': 1 },
        { 'source': 'LeadershipRoleExpansion', 'target': 'GlobalLeadershipConference', 'value': 1 },
        { 'source': 'GlobalLeadershipConference', 'target': 'FirstGlobalLeadershipPresentation', 'value': 1 },
        { 'source': 'FirstGlobalLeadershipPresentation', 'target': 'LeadershipMentorship', 'value': 1 },
        { 'source': 'LeadershipMentorship', 'target': 'FirstLeadershipMentee', 'value': 1 },
        { 'source': 'FirstLeadershipMentee', 'target': 'LeadershipGrowthPlan', 'value': 1 },
        { 'source': 'LeadershipGrowthPlan', 'target': 'Sabbatical', 'value': 1 },
        { 'source': 'Sabbatical', 'target': 'SabbaticalTravel', 'value': 1 },
        { 'source': 'SabbaticalTravel', 'target': 'SabbaticalResearch', 'value': 1 },
        { 'source': 'SabbaticalResearch', 'target': 'SabbaticalWriting', 'value': 1 },
        { 'source': 'SabbaticalWriting', 'target': 'PostRetirementEngagement', 'value': 1 },
        { 'source': 'PostRetirementEngagement', 'target': 'LegacyProjectStart', 'value': 2 },
        { 'source': 'LegacyProjectStart', 'target': 'FirstLegacyContribution', 'value': 1 },
        { 'source': 'FirstLegacyContribution', 'target': 'LegacyFoundationLaunch', 'value': 1 },
        { 'source': 'LegacyFoundationLaunch', 'target': 'FoundationFirstGrant', 'value': 1 },
        { 'source': 'FoundationFirstGrant', 'target': 'PhilanthropicLegacy', 'value': 1 },
        { 'source': 'PhilanthropicLegacy', 'target': 'LegacySchoolScholarship', 'value': 1 },
        { 'source': 'LegacySchoolScholarship', 'target': 'CommunityLegacyProject', 'value': 1 },
        { 'source': 'CommunityLegacyProject', 'target': 'GlobalLegacyImpact', 'value': 1 },
        { 'source': 'GlobalLegacyImpact', 'target': 'FinalProjectCompletion', 'value': 1 },
        { 'source': 'FinalProjectCompletion', 'target': 'LifeReflection', 'value': 1 },
        { 'source': 'LifeReflection', 'target': 'SpiritualRetreat', 'value': 1 },
        { 'source': 'SpiritualRetreat', 'target': 'LifeAchievementRecognition', 'value': 1 },
        { 'source': 'LifeAchievementRecognition', 'target': 'CommunityCelebration', 'value': 1 },
        { 'source': 'CommunityCelebration', 'target': 'FinalLegacyCelebration', 'value': 1 },
        { 'source': 'FinalLegacyCelebration', 'target': 'EstateFinalization', 'value': 1 },
        { 'source': 'EstateFinalization', 'target': 'FamilyInheritance', 'value': 1 },
        { 'source': 'FamilyInheritance', 'target': 'FinalGoodbye', 'value': 1 },
        { 'source': 'FinalGoodbye', 'target': 'MemorialService', 'value': 1 },
        { 'source': 'MemorialService', 'target': 'PosthumousRecognition', 'value': 1 },
        { 'source': 'PosthumousRecognition', 'target': 'LastWillExecution', 'value': 1 },
        { 'source': 'LastWillExecution', 'target': 'DigitalLegacyCreation', 'value': 1 },
        { 'source': 'DigitalLegacyCreation', 'target': 'FirstDigitalLegacy', 'value': 1 },
        { 'source': 'FirstDigitalLegacy', 'target': 'LegacyMediaRelease', 'value': 1 },
        { 'source': 'LegacyMediaRelease', 'target': 'PosthumousPublication', 'value': 1 },
        { 'source': 'PosthumousPublication', 'target': 'LegacyFoundationEndowment', 'value': 1 },
        { 'source': 'LegacyFoundationEndowment', 'target': 'PhilanthropicLegacy', 'value': 1 },
        { 'source': 'PhilanthropicLegacy', 'target': 'ImpactInvestmentStart', 'value': 1 },
        { 'source': 'ImpactInvestmentStart', 'target': 'FirstImpactInvestment', 'value': 1 },
        { 'source': 'FirstImpactInvestment', 'target': 'FirstCharitableDonation', 'value': 1 },
        { 'source': 'FirstCharitableDonation', 'target': 'SustainedCharitableSupport', 'value': 1 },
        { 'source': 'SustainedCharitableSupport', 'target': 'CharitableFoundation', 'value': 1 },
        { 'source': 'CharitableFoundation', 'target': 'FirstFoundationGrant', 'value': 1 },
        { 'source': 'FirstFoundationGrant', 'target': 'PhilanthropicRecognition', 'value': 1 },
        { 'source': 'PhilanthropicRecognition', 'target': 'SustainablePhilanthropy', 'value': 1 },
        { 'source': 'SustainablePhilanthropy', 'target': 'ImpactInvestmentStart', 'value': 1 },
        { 'source': 'ImpactInvestmentStart', 'target': 'ImpactInvestmentStart', 'value': 1 },
        // Add additional links as needed to reflect causal relationships
    ]
};


const miserablesDataset = {
    "nodes": [
        { "id": "Myriel", "group": 1 },
        { "id": "Napoleon", "group": 1 },
        { "id": "Mlle.Baptistine", "group": 1 },
        { "id": "Mme.Magloire", "group": 1 },
        { "id": "CountessdeLo", "group": 1 },
        { "id": "Geborand", "group": 1 },
        { "id": "Champtercier", "group": 1 },
        { "id": "Cravatte", "group": 1 },
        { "id": "Count", "group": 1 },
        { "id": "OldMan", "group": 1 },
        { "id": "Labarre", "group": 2 },
        { "id": "Valjean", "group": 2 },
        { "id": "Marguerite", "group": 3 },
        { "id": "Mme.deR", "group": 2 },
        { "id": "Isabeau", "group": 2 },
        { "id": "Gervais", "group": 2 },
        { "id": "Tholomyes", "group": 3 },
        { "id": "Listolier", "group": 3 },
        { "id": "Fameuil", "group": 3 },
        { "id": "Blacheville", "group": 3 },
        { "id": "Favourite", "group": 3 },
        { "id": "Dahlia", "group": 3 },
        { "id": "Zephine", "group": 3 },
        { "id": "Fantine", "group": 3 },
        { "id": "Mme.Thenardier", "group": 4 },
        { "id": "Thenardier", "group": 4 },
        { "id": "Cosette", "group": 5 },
        { "id": "Javert", "group": 4 },
        { "id": "Fauchelevent", "group": 0 },
        { "id": "Bamatabois", "group": 2 },
        { "id": "Perpetue", "group": 3 },
        { "id": "Simplice", "group": 2 },
        { "id": "Scaufflaire", "group": 2 },
        { "id": "Woman1", "group": 2 },
        { "id": "Judge", "group": 2 },
        { "id": "Champmathieu", "group": 2 },
        { "id": "Brevet", "group": 2 },
        { "id": "Chenildieu", "group": 2 },
        { "id": "Cochepaille", "group": 2 },
        { "id": "Pontmercy", "group": 4 },
        { "id": "Boulatruelle", "group": 6 },
        { "id": "Eponine", "group": 4 },
        { "id": "Anzelma", "group": 4 },
        { "id": "Woman2", "group": 5 },
        { "id": "MotherInnocent", "group": 0 },
        { "id": "Gribier", "group": 0 },
        { "id": "Jondrette", "group": 7 },
        { "id": "Mme.Burgon", "group": 7 },
        { "id": "Gavroche", "group": 8 },
        { "id": "Gillenormand", "group": 5 },
        { "id": "Magnon", "group": 5 },
        { "id": "Mlle.Gillenormand", "group": 5 },
        { "id": "Mme.Pontmercy", "group": 5 },
        { "id": "Mlle.Vaubois", "group": 5 },
        { "id": "Lt.Gillenormand", "group": 5 },
        { "id": "Marius", "group": 8 },
        { "id": "BaronessT", "group": 5 },
        { "id": "Mabeuf", "group": 8 },
        { "id": "Enjolras", "group": 8 },
        { "id": "Combeferre", "group": 8 },
        { "id": "Prouvaire", "group": 8 },
        { "id": "Feuilly", "group": 8 },
        { "id": "Courfeyrac", "group": 8 },
        { "id": "Bahorel", "group": 8 },
        { "id": "Bossuet", "group": 8 },
        { "id": "Joly", "group": 8 },
        { "id": "Grantaire", "group": 8 },
        { "id": "MotherPlutarch", "group": 9 },
        { "id": "Gueulemer", "group": 4 },
        { "id": "Babet", "group": 4 },
        { "id": "Claquesous", "group": 4 },
        { "id": "Montparnasse", "group": 4 },
        { "id": "Toussaint", "group": 5 },
        { "id": "Child1", "group": 10 },
        { "id": "Child2", "group": 10 },
        { "id": "Brujon", "group": 4 },
        { "id": "Mme.Hucheloup", "group": 8 }
    ],
    "links": [
        { "source": "Napoleon", "target": "Myriel", "value": 1 },
        { "source": "Mlle.Baptistine", "target": "Myriel", "value": 8 },
        { "source": "Mme.Magloire", "target": "Myriel", "value": 10 },
        { "source": "Mme.Magloire", "target": "Mlle.Baptistine", "value": 6 },
        { "source": "CountessdeLo", "target": "Myriel", "value": 1 },
        { "source": "Geborand", "target": "Myriel", "value": 1 },
        { "source": "Champtercier", "target": "Myriel", "value": 1 },
        { "source": "Cravatte", "target": "Myriel", "value": 1 },
        { "source": "Count", "target": "Myriel", "value": 2 },
        { "source": "OldMan", "target": "Myriel", "value": 1 },
        { "source": "Valjean", "target": "Labarre", "value": 1 },
        { "source": "Valjean", "target": "Mme.Magloire", "value": 3 },
        { "source": "Valjean", "target": "Mlle.Baptistine", "value": 3 },
        { "source": "Valjean", "target": "Myriel", "value": 5 },
        { "source": "Marguerite", "target": "Valjean", "value": 1 },
        { "source": "Mme.deR", "target": "Valjean", "value": 1 },
        { "source": "Isabeau", "target": "Valjean", "value": 1 },
        { "source": "Gervais", "target": "Valjean", "value": 1 },
        { "source": "Listolier", "target": "Tholomyes", "value": 4 },
        { "source": "Fameuil", "target": "Tholomyes", "value": 4 },
        { "source": "Fameuil", "target": "Listolier", "value": 4 },
        { "source": "Blacheville", "target": "Tholomyes", "value": 4 },
        { "source": "Blacheville", "target": "Listolier", "value": 4 },
        { "source": "Blacheville", "target": "Fameuil", "value": 4 },
        { "source": "Favourite", "target": "Tholomyes", "value": 3 },
        { "source": "Favourite", "target": "Listolier", "value": 3 },
        { "source": "Favourite", "target": "Fameuil", "value": 3 },
        { "source": "Favourite", "target": "Blacheville", "value": 4 },
        { "source": "Dahlia", "target": "Tholomyes", "value": 3 },
        { "source": "Dahlia", "target": "Listolier", "value": 3 },
        { "source": "Dahlia", "target": "Fameuil", "value": 3 },
        { "source": "Dahlia", "target": "Blacheville", "value": 3 },
        { "source": "Dahlia", "target": "Favourite", "value": 5 },
        { "source": "Zephine", "target": "Tholomyes", "value": 3 },
        { "source": "Zephine", "target": "Listolier", "value": 3 },
        { "source": "Zephine", "target": "Fameuil", "value": 3 },
        { "source": "Zephine", "target": "Blacheville", "value": 3 },
        { "source": "Zephine", "target": "Favourite", "value": 4 },
        { "source": "Zephine", "target": "Dahlia", "value": 4 },
        { "source": "Fantine", "target": "Tholomyes", "value": 3 },
        { "source": "Fantine", "target": "Listolier", "value": 3 },
        { "source": "Fantine", "target": "Fameuil", "value": 3 },
        { "source": "Fantine", "target": "Blacheville", "value": 3 },
        { "source": "Fantine", "target": "Favourite", "value": 4 },
        { "source": "Fantine", "target": "Dahlia", "value": 4 },
        { "source": "Fantine", "target": "Zephine", "value": 4 },
        { "source": "Fantine", "target": "Marguerite", "value": 2 },
        { "source": "Fantine", "target": "Valjean", "value": 9 },
        { "source": "Mme.Thenardier", "target": "Fantine", "value": 2 },
        { "source": "Mme.Thenardier", "target": "Valjean", "value": 7 },
        { "source": "Thenardier", "target": "Mme.Thenardier", "value": 13 },
        { "source": "Thenardier", "target": "Fantine", "value": 1 },
        { "source": "Thenardier", "target": "Valjean", "value": 12 },
        { "source": "Cosette", "target": "Mme.Thenardier", "value": 4 },
        { "source": "Cosette", "target": "Valjean", "value": 31 },
        { "source": "Cosette", "target": "Tholomyes", "value": 1 },
        { "source": "Cosette", "target": "Thenardier", "value": 1 },
        { "source": "Javert", "target": "Valjean", "value": 17 },
        { "source": "Javert", "target": "Fantine", "value": 5 },
        { "source": "Javert", "target": "Thenardier", "value": 5 },
        { "source": "Javert", "target": "Mme.Thenardier", "value": 1 },
        { "source": "Javert", "target": "Cosette", "value": 1 },
        { "source": "Fauchelevent", "target": "Valjean", "value": 8 },
        { "source": "Fauchelevent", "target": "Javert", "value": 1 },
        { "source": "Bamatabois", "target": "Fantine", "value": 1 },
        { "source": "Bamatabois", "target": "Javert", "value": 1 },
        { "source": "Bamatabois", "target": "Valjean", "value": 2 },
        { "source": "Perpetue", "target": "Fantine", "value": 1 },
        { "source": "Simplice", "target": "Perpetue", "value": 2 },
        { "source": "Simplice", "target": "Valjean", "value": 3 },
        { "source": "Simplice", "target": "Fantine", "value": 2 },
        { "source": "Simplice", "target": "Javert", "value": 1 },
        { "source": "Scaufflaire", "target": "Valjean", "value": 1 },
        { "source": "Woman1", "target": "Valjean", "value": 2 },
        { "source": "Woman1", "target": "Javert", "value": 1 },
        { "source": "Judge", "target": "Valjean", "value": 3 },
        { "source": "Judge", "target": "Bamatabois", "value": 2 },
        { "source": "Champmathieu", "target": "Valjean", "value": 3 },
        { "source": "Champmathieu", "target": "Judge", "value": 3 },
        { "source": "Champmathieu", "target": "Bamatabois", "value": 2 },
        { "source": "Brevet", "target": "Judge", "value": 2 },
        { "source": "Brevet", "target": "Champmathieu", "value": 2 },
        { "source": "Brevet", "target": "Valjean", "value": 2 },
        { "source": "Brevet", "target": "Bamatabois", "value": 1 },
        { "source": "Chenildieu", "target": "Judge", "value": 2 },
        { "source": "Chenildieu", "target": "Champmathieu", "value": 2 },
        { "source": "Chenildieu", "target": "Brevet", "value": 2 },
        { "source": "Chenildieu", "target": "Valjean", "value": 2 },
        { "source": "Chenildieu", "target": "Bamatabois", "value": 1 },
        { "source": "Cochepaille", "target": "Judge", "value": 2 },
        { "source": "Cochepaille", "target": "Champmathieu", "value": 2 },
        { "source": "Cochepaille", "target": "Brevet", "value": 2 },
        { "source": "Cochepaille", "target": "Chenildieu", "value": 2 },
        { "source": "Cochepaille", "target": "Valjean", "value": 2 },
        { "source": "Cochepaille", "target": "Bamatabois", "value": 1 },
        { "source": "Pontmercy", "target": "Thenardier", "value": 1 },
        { "source": "Boulatruelle", "target": "Thenardier", "value": 1 },
        { "source": "Eponine", "target": "Mme.Thenardier", "value": 2 },
        { "source": "Eponine", "target": "Thenardier", "value": 3 },
        { "source": "Anzelma", "target": "Eponine", "value": 2 },
        { "source": "Anzelma", "target": "Thenardier", "value": 2 },
        { "source": "Anzelma", "target": "Mme.Thenardier", "value": 1 },
        { "source": "Woman2", "target": "Valjean", "value": 3 },
        { "source": "Woman2", "target": "Cosette", "value": 1 },
        { "source": "Woman2", "target": "Javert", "value": 1 },
        { "source": "MotherInnocent", "target": "Fauchelevent", "value": 3 },
        { "source": "MotherInnocent", "target": "Valjean", "value": 1 },
        { "source": "Gribier", "target": "Fauchelevent", "value": 2 },
        { "source": "Mme.Burgon", "target": "Jondrette", "value": 1 },
        { "source": "Gavroche", "target": "Mme.Burgon", "value": 2 },
        { "source": "Gavroche", "target": "Thenardier", "value": 1 },
        { "source": "Gavroche", "target": "Javert", "value": 1 },
        { "source": "Gavroche", "target": "Valjean", "value": 1 },
        { "source": "Gillenormand", "target": "Cosette", "value": 3 },
        { "source": "Gillenormand", "target": "Valjean", "value": 2 },
        { "source": "Magnon", "target": "Gillenormand", "value": 1 },
        { "source": "Magnon", "target": "Mme.Thenardier", "value": 1 },
        { "source": "Mlle.Gillenormand", "target": "Gillenormand", "value": 9 },
        { "source": "Mlle.Gillenormand", "target": "Cosette", "value": 2 },
        { "source": "Mlle.Gillenormand", "target": "Valjean", "value": 2 },
        { "source": "Mme.Pontmercy", "target": "Mlle.Gillenormand", "value": 1 },
        { "source": "Mme.Pontmercy", "target": "Pontmercy", "value": 1 },
        { "source": "Mlle.Vaubois", "target": "Mlle.Gillenormand", "value": 1 },
        { "source": "Lt.Gillenormand", "target": "Mlle.Gillenormand", "value": 2 },
        { "source": "Lt.Gillenormand", "target": "Gillenormand", "value": 1 },
        { "source": "Lt.Gillenormand", "target": "Cosette", "value": 1 },
        { "source": "Marius", "target": "Mlle.Gillenormand", "value": 6 },
        { "source": "Marius", "target": "Gillenormand", "value": 12 },
        { "source": "Marius", "target": "Pontmercy", "value": 1 },
        { "source": "Marius", "target": "Lt.Gillenormand", "value": 1 },
        { "source": "Marius", "target": "Cosette", "value": 21 },
        { "source": "Marius", "target": "Valjean", "value": 19 },
        { "source": "Marius", "target": "Tholomyes", "value": 1 },
        { "source": "Marius", "target": "Thenardier", "value": 2 },
        { "source": "Marius", "target": "Eponine", "value": 5 },
        { "source": "Marius", "target": "Gavroche", "value": 4 },
        { "source": "BaronessT", "target": "Gillenormand", "value": 1 },
        { "source": "BaronessT", "target": "Marius", "value": 1 },
        { "source": "Mabeuf", "target": "Marius", "value": 1 },
        { "source": "Mabeuf", "target": "Eponine", "value": 1 },
        { "source": "Mabeuf", "target": "Gavroche", "value": 1 },
        { "source": "Enjolras", "target": "Marius", "value": 7 },
        { "source": "Enjolras", "target": "Gavroche", "value": 7 },
        { "source": "Enjolras", "target": "Javert", "value": 6 },
        { "source": "Enjolras", "target": "Mabeuf", "value": 1 },
        { "source": "Enjolras", "target": "Valjean", "value": 4 },
        { "source": "Combeferre", "target": "Enjolras", "value": 15 },
        { "source": "Combeferre", "target": "Marius", "value": 5 },
        { "source": "Combeferre", "target": "Gavroche", "value": 6 },
        { "source": "Combeferre", "target": "Mabeuf", "value": 2 },
        { "source": "Prouvaire", "target": "Gavroche", "value": 1 },
        { "source": "Prouvaire", "target": "Enjolras", "value": 4 },
        { "source": "Prouvaire", "target": "Combeferre", "value": 2 },
        { "source": "Feuilly", "target": "Gavroche", "value": 2 },
        { "source": "Feuilly", "target": "Enjolras", "value": 6 },
        { "source": "Feuilly", "target": "Prouvaire", "value": 2 },
        { "source": "Feuilly", "target": "Combeferre", "value": 5 },
        { "source": "Feuilly", "target": "Mabeuf", "value": 1 },
        { "source": "Feuilly", "target": "Marius", "value": 1 },
        { "source": "Courfeyrac", "target": "Marius", "value": 9 },
        { "source": "Courfeyrac", "target": "Enjolras", "value": 17 },
        { "source": "Courfeyrac", "target": "Combeferre", "value": 13 },
        { "source": "Courfeyrac", "target": "Gavroche", "value": 7 },
        { "source": "Courfeyrac", "target": "Mabeuf", "value": 2 },
        { "source": "Courfeyrac", "target": "Eponine", "value": 1 },
        { "source": "Courfeyrac", "target": "Feuilly", "value": 6 },
        { "source": "Courfeyrac", "target": "Prouvaire", "value": 3 },
        { "source": "Bahorel", "target": "Combeferre", "value": 5 },
        { "source": "Bahorel", "target": "Gavroche", "value": 5 },
        { "source": "Bahorel", "target": "Courfeyrac", "value": 6 },
        { "source": "Bahorel", "target": "Mabeuf", "value": 2 },
        { "source": "Bahorel", "target": "Enjolras", "value": 4 },
        { "source": "Bahorel", "target": "Feuilly", "value": 3 },
        { "source": "Bahorel", "target": "Prouvaire", "value": 2 },
        { "source": "Bahorel", "target": "Marius", "value": 1 },
        { "source": "Bossuet", "target": "Marius", "value": 5 },
        { "source": "Bossuet", "target": "Courfeyrac", "value": 12 },
        { "source": "Bossuet", "target": "Gavroche", "value": 5 },
        { "source": "Bossuet", "target": "Bahorel", "value": 4 },
        { "source": "Bossuet", "target": "Enjolras", "value": 10 },
        { "source": "Bossuet", "target": "Feuilly", "value": 6 },
        { "source": "Bossuet", "target": "Prouvaire", "value": 2 },
        { "source": "Bossuet", "target": "Combeferre", "value": 9 },
        { "source": "Bossuet", "target": "Mabeuf", "value": 1 },
        { "source": "Bossuet", "target": "Valjean", "value": 1 },
        { "source": "Joly", "target": "Bahorel", "value": 5 },
        { "source": "Joly", "target": "Bossuet", "value": 7 },
        { "source": "Joly", "target": "Gavroche", "value": 3 },
        { "source": "Joly", "target": "Courfeyrac", "value": 5 },
        { "source": "Joly", "target": "Enjolras", "value": 5 },
        { "source": "Joly", "target": "Feuilly", "value": 5 },
        { "source": "Joly", "target": "Prouvaire", "value": 2 },
        { "source": "Joly", "target": "Combeferre", "value": 5 },
        { "source": "Joly", "target": "Mabeuf", "value": 1 },
        { "source": "Joly", "target": "Marius", "value": 2 },
        { "source": "Grantaire", "target": "Bossuet", "value": 3 },
        { "source": "Grantaire", "target": "Enjolras", "value": 3 },
        { "source": "Grantaire", "target": "Combeferre", "value": 1 },
        { "source": "Grantaire", "target": "Courfeyrac", "value": 2 },
        { "source": "Grantaire", "target": "Joly", "value": 2 },
        { "source": "Grantaire", "target": "Gavroche", "value": 1 },
        { "source": "Grantaire", "target": "Bahorel", "value": 1 },
        { "source": "Grantaire", "target": "Feuilly", "value": 1 },
        { "source": "Grantaire", "target": "Prouvaire", "value": 1 },
        { "source": "MotherPlutarch", "target": "Mabeuf", "value": 3 },
        { "source": "Gueulemer", "target": "Thenardier", "value": 5 },
        { "source": "Gueulemer", "target": "Valjean", "value": 1 },
        { "source": "Gueulemer", "target": "Mme.Thenardier", "value": 1 },
        { "source": "Gueulemer", "target": "Javert", "value": 1 },
        { "source": "Gueulemer", "target": "Gavroche", "value": 1 },
        { "source": "Gueulemer", "target": "Eponine", "value": 1 },
        { "source": "Babet", "target": "Thenardier", "value": 6 },
        { "source": "Babet", "target": "Gueulemer", "value": 6 },
        { "source": "Babet", "target": "Valjean", "value": 1 },
        { "source": "Babet", "target": "Mme.Thenardier", "value": 1 },
        { "source": "Babet", "target": "Javert", "value": 2 },
        { "source": "Babet", "target": "Gavroche", "value": 1 },
        { "source": "Babet", "target": "Eponine", "value": 1 },
        { "source": "Claquesous", "target": "Thenardier", "value": 4 },
        { "source": "Claquesous", "target": "Babet", "value": 4 },
        { "source": "Claquesous", "target": "Gueulemer", "value": 4 },
        { "source": "Claquesous", "target": "Valjean", "value": 1 },
        { "source": "Claquesous", "target": "Mme.Thenardier", "value": 1 },
        { "source": "Claquesous", "target": "Javert", "value": 1 },
        { "source": "Claquesous", "target": "Eponine", "value": 1 },
        { "source": "Claquesous", "target": "Enjolras", "value": 1 },
        { "source": "Montparnasse", "target": "Javert", "value": 1 },
        { "source": "Montparnasse", "target": "Babet", "value": 2 },
        { "source": "Montparnasse", "target": "Gueulemer", "value": 2 },
        { "source": "Montparnasse", "target": "Claquesous", "value": 2 },
        { "source": "Montparnasse", "target": "Valjean", "value": 1 },
        { "source": "Montparnasse", "target": "Gavroche", "value": 1 },
        { "source": "Montparnasse", "target": "Eponine", "value": 1 },
        { "source": "Montparnasse", "target": "Thenardier", "value": 1 },
        { "source": "Toussaint", "target": "Cosette", "value": 2 },
        { "source": "Toussaint", "target": "Javert", "value": 1 },
        { "source": "Toussaint", "target": "Valjean", "value": 1 },
        { "source": "Child1", "target": "Gavroche", "value": 2 },
        { "source": "Child2", "target": "Gavroche", "value": 2 },
        { "source": "Child2", "target": "Child1", "value": 3 },
        { "source": "Brujon", "target": "Babet", "value": 3 },
        { "source": "Brujon", "target": "Gueulemer", "value": 3 },
        { "source": "Brujon", "target": "Thenardier", "value": 3 },
        { "source": "Brujon", "target": "Gavroche", "value": 1 },
        { "source": "Brujon", "target": "Eponine", "value": 1 },
        { "source": "Brujon", "target": "Claquesous", "value": 1 },
        { "source": "Brujon", "target": "Montparnasse", "value": 1 },
        { "source": "Mme.Hucheloup", "target": "Bossuet", "value": 1 },
        { "source": "Mme.Hucheloup", "target": "Joly", "value": 1 },
        { "source": "Mme.Hucheloup", "target": "Grantaire", "value": 1 },
        { "source": "Mme.Hucheloup", "target": "Bahorel", "value": 1 },
        { "source": "Mme.Hucheloup", "target": "Courfeyrac", "value": 1 },
        { "source": "Mme.Hucheloup", "target": "Gavroche", "value": 1 },
        { "source": "Mme.Hucheloup", "target": "Enjolras", "value": 1 }
    ]
};
